version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "project infrastructure"

  # Docker
  - package-ecosystem: "docker"
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: "daily"
    labels:
      - "project infrastructure"

  # Python
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_slug}}"
    schedule:
      interval: "daily"
    labels:
      - "project infrastructure"

    