services:
  api:
    container_name: teste_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: teste_api_dev

    ports:
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: /bin/bash -c "/app/pre-start.sh && uv run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"

  postgres:
    container_name: teste_postgresql_dev
    image: postgres:16

    ports:
      - "5432:5432"
    volumes:
      - ./pre-start-db-test.sql:/docker-entrypoint-initdb.d/pre-start-db-test.sql
      - postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${USUARIO_POSTGRES}
      - POSTGRES_PASSWORD=${SENHA_POSTGRES}
      - POSTGRES_DB=${BD_POSTGRES}
      - BD_POSTGRES_TESTE=${BD_POSTGRES_TESTE}

  redis:
    container_name: teste_redis_dev
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
