"""init

Revision ID: 4954d8d595d5
Revises: 
Create Date: 2025-04-29 21:52:01.064833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4954d8d595d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primeiro_nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('permissao', sa.String(), nullable=False),
    sa.Column('senha_criptografada', sa.String(), nullable=False),
    sa.Column('esta_ativo', sa.Boolean(), nullable=True),
    sa.Column('eh_superusuario', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_primeiro_nome'), 'usuarios', ['primeiro_nome'], unique=False)
    op.create_index(op.f('ix_usuarios_sobrenome'), 'usuarios', ['sobrenome'], unique=False)
    op.create_index(op.f('ix_usuarios_telefone'), 'usuarios', ['telefone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_telefone'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_sobrenome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_primeiro_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
